# Generated by Django 3.1.5 on 2021-01-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fono',
            field=models.IntegerField(),
        ),
    ]
