# Generated by Django 3.1.5 on 2021-01-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20210122_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fono',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
